apiVersion: v1
description: 'elasticsearch-stash by AppsCode - Elasticsearch database backup and restore plugin for Stash.'
name: elasticsearch-stash
version: 6.3
appVersion: 6.3
home: https://github.com/stashed/elasticsearch
icon: https://cdn.appscode.com/images/icon/stash.png
sources:
  - https://github.com/stashed/elasticsearch
maintainers:
  - name: appscode
    email: support@appscode.com
