apiVersion: stash.appscode.com/v1beta1
kind: Task
metadata:
  name: elasticsearch-backup-{{- include "stash-elasticsearch.versionSuffix" . }}
  labels:
    {{- include "stash-elasticsearch.labels" . | nindent 4 }}
spec:
  steps:
  - name: elasticsearch-backup-{{- include "stash-elasticsearch.versionSuffix" . }}
    params:
    - name: outputDir
      value: /tmp/output
    - name: secretVolume
      value: secret-volume
  - name: update-status
    params:
    - name: outputDir
      value: /tmp/output
  volumes:
  - name: secret-volume
    secret:
      secretName: ${REPOSITORY_SECRET_NAME}
  - name: data
  {{- if .Values.persistence.enabled }}
    persistentVolumeClaim:
      claimName: {{ .Values.persistence.existingClaim | default (printf "datadir-%s" (include "stash-elasticsearch.versionSuffix" . )) }}
  {{- else }}
    emptyDir: {}
  {{- end }}
