# Default values for stash-elasticsearch.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

nameOverride: ""
fullnameOverride: ""

image:
  registry: stashed
  repository: stash-elasticsearch
  tag: "6.2.4"

# optional argument to send multielasticdump
backup:
  args: ""
restore:
  args: ""
